# Generated by Django 3.1 on 2020-04-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200429_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
